apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vultacore-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: api.vultacore.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vultacore-api
            port:
              number: 80
  tls:
  - hosts:
    - api.vultacore.com
    secretName: vultacore-api-tls
